Task-1
thitrylynx/backbone-training-project pull request #1
Opened 2018-11-07 07:59 UTC by thitrylynx

-Добавил package.json с backbone, jquery, loash, настроил сборку
-Сверстал форму ввода артикула

2018-11-07 08:10 UTC, mtrsv requested changes

2018-11-07 08:10 UTC, mtrsv commented on src/app.js
> +import './scss/typography.scss';
Не хватает пустой строки в конце файла.
В всех файлах, где гитхаб показывает значок:
![image](https://user-images.githubusercontent.com/19954042/48118446-1a57df80-e28e-11e8-96e2-efffffe95252.png)

2018-11-07 08:10 UTC, mtrsv commented on src/scss/typography.scss
> +h1 {
Не привязываем стили к тегам, только к классам

2018-11-07 08:10 UTC, mtrsv commented on src/scss/search-form.scss
> +div {
Не привязываем стили к тегам, только к классам

2018-11-08 03:46 UTC, thitrylynx commented on src/app.js
> +import './scss/typography.scss';
Fixed

2018-11-08 03:46 UTC, thitrylynx commented on src/scss/typography.scss
> +h1 {
Fixed

2018-11-08 03:46 UTC, thitrylynx commented on src/scss/search-form.scss
> +div {
Fixed

2018-11-09 18:01 UTC, mtrsv approved these changes

2018-11-10 04:21 UTC, merged